--ALTER SESSION SET CURRENT_SCHEMA = ADVENTUREWORKS;

--Drop existing tables

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE AdventureWorksDWBuildVersion CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE DimAccount CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE DimCurrency CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE DimCustomer CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE DimDate CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE DimDepartmentGroup CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE DimEmployee CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE DimGeography CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE DimOrganization CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE DimProduct CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE DimProductCategory CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE DimProductSubcategory CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE DimPromotion CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE DimReseller CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE DimSalesReason CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE DimSalesTerritory CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE DimScenario CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE FactAdditionalInternationalProductDescription CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE FactCallCenter CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE FactCurrencyRate CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE FactFinance CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE FactInternetSales CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE FactInternetSalesReason CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE FactProductInventory CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE FactResellerSales CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE FactSalesQuota CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE FactSurveyResponse CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE NewFactCurrencyRate CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE ProspectiveBuyer CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE sysdiagrams CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE DatabaseLog CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        NULL; -- Ignore errors if the tables do not exist
END;


